services:
  immich-lite:
    image: nginx:alpine
    container_name: immich-lite
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      - IMMICH_URL=http://X.X.X.X:2283
    volumes:
      - /opt/immich-lite:/usr/share/nginx/html:ro
      - /opt/immich-lite/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
networks:
  immich_default:
    external: true
